"""add growth measurements and care logs

Revision ID: 2ac97411e886
Revises: f39aa7bdfcca
Create Date: 2026-09-20 19:04:49.815207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac97411e886'
down_revision: Union[str, Sequence[str], None] = 'f39aa7bdfcca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('caregiver_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('FEED', 'DIAPER', 'SLEEP', 'MEDICATION', name='care_log_type'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('growth_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('measured_at', sa.Date(), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('source_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('growth_measurements')
    op.drop_table('care_logs')
    # ### end Alembic commands ###
    # Autogenerate doesn't emit this for Postgres ENUM types: dropping the
    # 'care_logs' table does not drop the 'care_log_type' type, so a
    # re-upgrade after this downgrade would otherwise fail with
    # "type care_log_type already exists".
    sa.Enum(name='care_log_type').drop(op.get_bind(), checkfirst=True)
