"""add name to children

Revision ID: 57e4b0fdb1ee
Revises: 2ac97411e886
Create Date: 2026-09-20 20:22:36.949877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e4b0fdb1ee'
down_revision: Union[str, Sequence[str], None] = '2ac97411e886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'name')
    # ### end Alembic commands ###
