"""add help requests

Revision ID: c4b260e4db30
Revises: ea8bd9530f5a
Create Date: 2026-09-21 19:37:40.636984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b260e4db30'
down_revision: Union[str, Sequence[str], None] = 'ea8bd9530f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('need_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLAIMED', 'COMPLETED', name='help_request_status'), nullable=False),
    sa.Column('claimed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('help_requests')
    # ### end Alembic commands ###
    # Autogenerate never emits this for an ENUM owned by a dropped table --
    # same recurring gap as care_log_type/appointment_status.
    sa.Enum(name='help_request_status').drop(op.get_bind(), checkfirst=True)
