"""add caregiver is_provider flag and screening responses

Revision ID: ea8bd9530f5a
Revises: f23c276be9d3
Create Date: 2026-09-21 19:23:11.648944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8bd9530f5a'
down_revision: Union[str, Sequence[str], None] = 'f23c276be9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caregiver_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('item_10_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('caregivers', sa.Column('is_provider', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caregivers', 'is_provider')
    op.drop_table('screening_responses')
    # ### end Alembic commands ###
