"""add caregiver auth fields and schedule item detail

Revision ID: f39aa7bdfcca
Revises: 618196d8e81a
Create Date: 2026-09-20 18:01:18.150114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39aa7bdfcca'
down_revision: Union[str, Sequence[str], None] = '618196d8e81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caregivers', sa.Column('email', sa.String(), nullable=False))
    op.add_column('caregivers', sa.Column('password_hash', sa.String(), nullable=False))
    op.create_unique_constraint('uq_caregivers_email', 'caregivers', ['email'])
    op.add_column('schedule_items', sa.Column('vaccine_id', sa.String(), nullable=False))
    op.add_column('schedule_items', sa.Column('dose_number', sa.Integer(), nullable=True))
    op.add_column('schedule_items', sa.Column('administered_date', sa.Date(), nullable=True))
    op.add_column('schedule_items', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_items', 'notes')
    op.drop_column('schedule_items', 'administered_date')
    op.drop_column('schedule_items', 'dose_number')
    op.drop_column('schedule_items', 'vaccine_id')
    op.drop_constraint('uq_caregivers_email', 'caregivers', type_='unique')
    op.drop_column('caregivers', 'password_hash')
    op.drop_column('caregivers', 'email')
    # ### end Alembic commands ###
